export const RANDOM_CATEGORIES = [
  "Space",
  "History",
  "Science",
  "Technology",
  "Nature",
  "Animals",
  "Food",
  "Sports",
  "Music",
  "Movies",
  "Books",
  "Art",
  "Geography",
  "Travel",
  "Health",
  "Psychology",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Astronomy",
  "Engineering",
  "Architecture",
  "Literature",
  "Philosophy",
  "Economics",
  "Politics",
  "Culture",
  "Languages",
  "Education",
  "Environment",
  "Weather",
  "Fashion",
  "Games",
  "Comics",
  "Television",
  "Theater",
  "Dance",
  "Photography",
  "Magic",
  "Folklore",
  "Mythology",
  "Religion",
  "Astrology",
  "Zoology",
  "Botany",
  "Genetics",
  "Ecology",
  "Marine Biology",
  "Microbiology",
  "Neuroscience",
  "Robotics",
  "Artificial Intelligence",
  "Quantum Mechanics",
  "Nanotechnology",
  "Space Exploration",
  "Renewable Energy",
  "Climate Change",
  "Conservation",
  "Wildlife",
  "Forests",
  "Oceans",
  "Mountains",
  "Deserts",
  "Rivers",
  "Lakes",
  "Volcanoes",
  "Earthquakes",
  "Tsunamis",
  "Hurricanes",
  "Tornadoes",
  "Blizzards",
  "Floods",
  "Droughts",
  "Fossils",
  "Dinosaurs",
  "Evolution",
  "Human Body",
  "Medicine",
  "Nutrition",
  "Fitness",
  "Mental Health",
  "Sleep",
  "Dreams",
  "Memory",
  "Learning",
  "Creativity",
  "Productivity",
  "Time Management",
  "Motivation",
  "Leadership",
  "Communication",
  "Relationships",
  "Parenting",
  "Child Development",
  "Education Systems",
  "Teaching Methods",
  "Learning Styles",
  "Study Techniques",
  "Exams",
  "Homework",
  "School Life",
  "College Life",
  "Career Planning",
  "Job Hunting",
  "Resumes",
  "Interviews",
  "Workplace Culture",
  "Work-Life Balance",
  "Entrepreneurship",
  "Startups",
  "Business Models",
  "Marketing",
  "Sales",
  "Customer Service",
  "Finance",
  "Investing",
  "Stock Market",
  "Real Estate",
  "Taxes",
  "Insurance",
  "Retirement",
  "Personal Finance",
  "Budgeting",
  "Saving",
  "Spending",
  "Debt",
  "Credit",
  "Banking",
  "Cryptocurrency",
  "Blockchain",
  "Economics Theories",
  "Global Economy",
  "Trade",
  "Inflation",
  "Recession",
  "Unemployment",
  "Poverty",
  "Inequality",
  "Social Justice",
  "Human Rights",
  "Law",
  "Crime",
  "Punishment",
  "Prisons",
  "Police",
  "Courts",
  "Politics Systems",
  "Governments",
  "Elections",
  "Political Parties",
  "Public Policy",
  "International Relations",
  "War",
  "Peace",
  "Military",
  "Espionage",
  "Terrorism",
  "Diplomacy",
  "United Nations",
  "European Union",
  "NATO",
  "World Bank",
  "IMF",
  "NGOs",
  "Charities",
  "Volunteering",
  "Community Service",
  "Social Movements",
  "Protests",
  "Activism",
  "Environmentalism",
  "Sustainability",
  "Recycling",
  "Green Energy",
  "Electric Vehicles",
  "Public Transport",
  "Urban Planning",
  "Smart Cities",
  "Rural Development",
  "Agriculture",
  "Farming",
  "Food Production",
  "Food Security",
  "Water Resources",
  "Sanitation",
  "Hygiene",
  "Public Health",
  "Healthcare Systems",
  "Medical Research",
  "Vaccines",
  "Pandemics",
  "Epidemiology",
  "Genomics",
  "Biotechnology",
  "Pharmaceuticals",
  "Medical Devices",
  "Telemedicine",
  "Health Insurance",
  "Patient Care",
  "Emergency Medicine",
  "Surgery",
  "Anatomy",
  "Physiology",
  "Pathology",
  "Radiology",
  "Oncology",
  "Cardiology",
  "Neurology",
  "Psychiatry",
  "Psychology Theories",
  "Behavioral Science",
  "Cognitive Science",
  "Developmental Psychology",
  "Social Psychology",
  "Clinical Psychology",
  "Counseling",
  "Therapy",
  "Rehabilitation",
  "Special Education",
  "Gifted Education",
  "Early Childhood Education",
  "Primary Education",
  "Secondary Education",
  "Higher Education",
  "Personalized Learning",
  "Adaptive Learning",
  "Competency-Based Learning",
  "Mastery Learning",
  "Self-Directed Learning",
  "Educational Research",
  "Education Policy",
  "School Administration",
  "Educational Leadership",
  "School Management",
  "School Safety",
  "Bullying",
  "Cyberbullying",
  "School Sports",
  "Physical Education",
  "School Clubs",
  "Extracurricular Activities",
  "Field Trips",
  "School Events",
  "School Traditions",
  "School Culture",
  "School Spirit",
  "School Uniforms",
  "School Boards",
  "School Districts",
  "State Education Departments",
  "Federal Education Agencies",
  "International Education Organizations",
  "Education Conferences",
  "Education Journals",
  "Education Blogs",
  "Education Podcasts",
  "Education Videos",
  "Education Webinars",
  "Education Workshops",
  "Education Materials",
  "Education Technologies",
  "Education Innovations",
  "Education Trends",
];
