RANDOM_CATEGORIES = [
    "science",
    "history",
    "technology",
    "nature",
    "space",
    "animals",
    "geography",
    "literature",
    "art",
    "music",
    "movies",
    "sports",
    "food",
    "health",
    "psychology",
    "philosophy",
    "mathematics",
    "physics",
    "chemistry",
    "biology",
    "astronomy",
    "engineering",
    "architecture",
    "economics",
    "politics",
    "sociology",
    "anthropology",
    "archaeology",
    "linguistics",
    "education",
    "law",
    "business",
    "marketing",
    "finance",
    "cryptocurrency",
    "robotics",
    "artificial intelligence",
    "machine learning",
    "data science",
    "programming",
    "web development",
    "cybersecurity",
    "networking",
    "cloud computing",
    "blockchain",
    "quantum computing",
    "nanotechnology",
    "biotechnology",
    "genetics",
    "neuroscience",
    "medicine",
    "pharmacology",
    "veterinary science",
    "agriculture",
    "environment",
    "climate change",
    "renewable energy",
    "sustainable development",
    "urban planning",
    "transportation",
    "aviation",
    "marine biology",
    "oceanography",
    "meteorology",
    "geology",
    "volcanology",
    "seismology",
    "paleontology",
    "astronautics",
    "space exploration",
    "extraterrestrial life",
    "science fiction",
    "fantasy",
    "mythology",
    "folklore",
    "religion",
    "spirituality",
    "ethics",
    "media studies",
    "communication",
    "journalism",
    "photography",
    "film studies",
    "theater",
    "dance",
    "fashion",
    "design",
    "crafts",
    "gardening",
    "hiking",
    "travel",
    "adventure",
    "gaming",
    "puzzles",
    "board games",
    "card games",
    "video games",
    "virtual reality",
    "augmented reality",
    "mixed reality",
    "3D printing",
    "drones",
    "wearable technology",
    "smart homes",
    "internet of things",
    "home automation",
    "self-driving cars",
    "electric vehicles",
    "space tourism",
    "teleportation",
    "time travel",
    "parallel universes",
    "multiverse",
    "string theory",
    "dark matter",
    "dark energy",
    "black holes",
    "wormholes",
    "supernovae",
    "neutron stars",
    "quasars",
    "pulsars",
    "cosmic rays",
    "gravitational waves",
    "exoplanets",
    "habitable zones",
    "astrobiology",
    "astrochemistry",
    "astrophysics",
    "cosmology",
    "galaxies",
    "nebulae",
    "star formation",
    "planetary science",
    "solar system",
    "sun",
    "moon",
    "planets",
    "asteroids",
    "comets",
    "meteors",
    "meteorites",
    "space debris",
    "space weather",
    "space missions",
    "spacecraft",
    "satellites",
    "space stations",
    "space telescopes",
    "space probes",
]
