"on":
    push:
        branches:
            - main
name: Deploy to arxiv
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: exec porter apply -f ./21102024-ArXiv/server/porter.yaml
              env:
                PORTER_APP_NAME: arxiv
                PORTER_CLUSTER: "2226"
                PORTER_DEPLOYMENT_TARGET_ID: 580598f7-dff6-448a-8565-289ed087c1b8
                PORTER_HOST: https://cloud.porter.run
                PORTER_PR_NUMBER: ${{ github.event.number }}
                PORTER_PROJECT: "2339"
                PORTER_REPO_NAME: ${{ github.event.repository.name }}
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_STACK_2339_2226 }}
